# Makefile

all: programaTrab

programaTrab.o: programaTrab.c funcoesFile.h
	gcc -o programaTrab.o programaTrab.c -c -Wall

funcoesFile.o: funcoesFile.c funcoesFile.h
	gcc -o funcoesFile.o funcoesFile.c -c -Wall

run:
	./programaTrab